### ISSUE TITLE
Some bugs in Kubuntu 20.10

### ISSUE THREAD

**Issue by OlegoroV** [brunoherbelin/vimix#12]
1. "Import a file" dialog opens behind main window.
2. Drag'n'droping a file into main window freezes a program.
3. Cyrillic file names display as question marks.

Version 0.4 snap.

**Comment by brunoherbelin** [comment]
Thanks for your report.
Difficult to reproduce.. Maybe specific to KDE? Below some suggestions

1. Dialog behind
vimix uses https://github.com/native-toolkit/tinyfiledialogs for system dialogs: one should wait  that the dialog appears, make sure to avoid clicking meanwhile...

2. Drag'n drop
Could not reproduce: maybe the file caused a crash? Open the logs (CTRL+L) to see the message.
Please give more info.

3. Cyrillic
Which display? in dialog ? 
plse send a file with cyrillic filename to be tested.

Please do not hesitate to propose bug fix (I can also accept pull requests in git).

**Comment by OlegoroV** [comment]
Hello!I recorded a video. You can see there all bugs. And it has cyrillic symbols in its name.When Vimix freezes I cannot see log. After restart log is clear (only current session info).https://yadi.sk/i/nvG7d-wEhwzi_w23.11.2020, 21:28, "BHBN" <notifications@github.com>:
Thanks for your report.
Difficult to reproduce.. Maybe specific to KDE? Below some suggestions


Dialog behind
vimix uses https://github.com/native-toolkit/tinyfiledialogs for system dialogs: one should wait  that the dialog appears, make sure to avoid clicking meanwhile...


Drag'n drop
Could not reproduce: maybe the file caused a crash? Open the logs (CTRL+L) to see the message.
Please give more info.


Cyrillic
Which display? in dialog ?
plse send a file with cyrillic filename to be tested.


Please do not hesitate to propose bug fix (I can also accept pull requests in git).

**Comment by brunoherbelin** [comment]
Regarding the issue with the Cyrillic text, I have one solution to offer (you can test it in the last release 0.4.3); I implemented a basic transliteration of the filenames to generate the name of the source; it still work-in-progress and will need to be improved to display filenames.

The video didn't allow identifying which window manager you have: is it xfce? kde? This could be the reason why the file dialog appears behind the main window... 
What I notice though is that the framerate is not v-synched : did you change some settings?

**Comment by OlegoroV** [comment]
Cyrillic transliterated successfully. Drag'n'dropping video works. Thank you!

Window manager is KDE. OS is Kubuntu 20.10.
Open file dialog is still behind main window.
V-sync in preferences is ON but it seems that it's not working.

And I've got new bugs:
1. When drag main window to another display, program freezes. Refresh FPS stops, but when I move window it updates.
2. New empty session dont use GPU. Then add any video. Speed of fan and GPU temperature are at maximum. Process uses 16% of CPU, 98% of GPU and 35% of GPU memory(GPU total memory is 2GB). Then I move out all videos from mixing circle. Now process uses 12% of CPU, 98% of GPU and 28% of GPU memory. Even starting new empty session does't help. And after restarting program GPU is unused for some time. But then (I still don't know when) process again starts use 98% of GPU.

**Comment by brunoherbelin** [comment]
Good! we are progressing!

There is definitely a problem with the v-sync: this explains both the freeze of display (and update only on window change) and the high GPU usage (no v-sync means GPU tries to render as many frames as possible up to its maximum capacity). 

Please try to change your graphics driver options (which could override the request for v-sync and disable it systemwide).

Still, I will keep it under the TODO list to provide a software emulation of v-sync, so as to offer an alternative for some systems...

**Comment by OlegoroV** [comment]
Just reinstalled nvidia drivers (and deleted /etc/X11/xorg.conf and something esle with default nvidia settings in the same directory). And now in NVidia settings I see that syncronisation is ON. And Vimix works with 60FPS. But still freezes when moving its windows betweeen screens.

**Comment by OlegoroV** [comment]
New problems with Kubuntu 20.10.
Cannot open any file. Vimix writes - File does not exist.
Open file dialog even doesn't appears.

![image](https://user-images.githubusercontent.com/74917360/111956730-2ad62100-8afc-11eb-8f6d-3c95058f0cc7.png)

**Comment by brunoherbelin** [comment]
Looks like the dialog is not able to launch under KDE :(, thus the empty filename (not existing).
Can you please make sure your system has zenity installed ? : https://doc.ubuntu-fr.org/zenity
Are you using the snap? Latest edge?

**Comment by brunoherbelin** [comment]
ok, same under Gnome. Looks like a snap problem... will fix it ASAP

**Comment by brunoherbelin** [comment]
Thanks Oleg for pointing out this issue. I spent the last two weeks repairing the snap which was (suddenly) not accepting the UI dialogs I was using.

Could you please get the latest edge snap to tell me if this also works under KDE?

**Comment by OlegoroV** [comment]
It works!!! Thank You!
